Dictionary/dictionary/urls.py
from django.urls import path
from . import views

app_name="dictionary"

urlpatterns=[path('',views.home,name="home"),
		path('meaning/',views.meaning,name='meaning'),
        ]

Dictionary/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('dictionary/',include('dictionary.urls')),
    path('calculator/',include('calculator.urls')),
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),

]

Dictionary/dictionary/models.py
from django.db import models

# Create your models here.

Dictionary/dictionary/views.py
from django.shortcuts import render
from nltk.corpus import wordnet
from urllib.request import urlopen,urlretrieve,Request
from urllib.error import HTTPError
from bs4 import BeautifulSoup
import os,shutil
from django import template
# Create your views here.


def get_audio(url,word):
    try:
        url=Request(url,headers={"User-Agent":"Mozilla/5.0"})
        html=urlopen(url)
    except HTTPError as e:
        print(e)
        return
    try:
        bsobj=BeautifulSoup(html,"html.parser")
        data=bsobj.find("div",{"id":"base-pw"}).find("audio").findAll("source")
        urlretrieve(data[1]['src'],'%s_new.mp3'%word)
        shutil.move('/home/saurabh/basic_django/mysite/%s_new.mp3'%word,'/home/saurabh/basic_django/mysite/dictionary/static/%s_new.mp3'%word)

    except AttributeError as e:
        print(e)
        return

def home(request):
	return render(request,'home.html')

def meaning(request):
	word=request.POST["search"]
	url="https://www.dictionary.com/browse/%s?s=t"%word
	get_audio(url,word)
	name='%s_new.mp3'%word
	data=wordnet.synsets(word)

	try:
		heading=data[0].lemmas()[0].name()
		define=data[0].definition()
	except:
		heading=None
		define=None
	examples=[]
	synonyms=set()
	antonyms=set()
	for d in data:
		examples.append(d.examples())
		for l in d.lemmas():
			synonyms.add(l.name())
			if l.antonyms():
				for a in l.antonyms():
					antonyms.add(a.name())
	examples=examples[:3]
	context={'name':name,'heading':heading,'define':define,'examples':examples,'synonyms':synonyms,'antonyms':antonyms}
	return render(request,'content.html',context)

Dictionary/dictionary/templates/content.html
{% extends 'home.html' %}
{% block content %}
<div>
	{% load static %}
	<h1 style="color:blue">{{heading}}</h1>
	 <audio id="player" src="{% static name %}"></audio>
    <div>
         <a onclick="document.getElementById('player').play()"><i class='fa fa-volume-up fa-2x'></i></a>
     </div> 
	<br>
		<strong style="color:red">Definition</strong><h2>{{define}}</h2>
	{% if examples %}
		<strong style="color:red">Examples-:</strong>
		{% for e in examples %}
			{% if e %}
			<h3>{{e}}</h3>
			{% endif %}
		{% endfor %}
	{% endif %}
	<br>
	{% if synonyms %}
	<strong style="color:red">Synonyms:</strong>
		{% for s in synonyms %}
			<p>{{ s}}</p>
		{% endfor %}
	{% endif %}

	{% if antonyms %}
	<strong style="color:red">Antonyms:</strong>
		{% for a in antonyms %}
			<p>{{a}},</p>
		{% endfor %}
	{% endif %}
</div>
{% endblock %}

Dictionary/dictionary/templates/home.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
  font-family: Arial;
}

* {
  box-sizing: border-box;
}

form.example input[type=text] {
  padding: 10px;
  font-size: 17px;
  border: 1px solid grey;
  float: left;
  width: 80%;
  background: #f1f1f1;
}

form.example button {
  float: left;
  width: 20%;
  padding: 10px;
  background: #2196F3;
  color: white;
  font-size: 17px;
  border: 1px solid grey;
  border-left: none;
  cursor: pointer;
}

form.example button:hover {
  background: #0b7dda;
}

form.example::after {
  content: "";
  clear: both;
  display: table;
}
</style>
</head>
<body>
<form class="example" action="{% url 'dictionary:meaning' %}" style="margin:auto;max-width:300px" method="post">
  {% csrf_token %}
  <input type="text" placeholder="Search.." name="search">
  <button type="submit"><i class="fa fa-search"></i></button>
</form>
{% block content %}
{% endblock %}

</body>
</html> 